
FROM gitlab-master.nvidia.com:5005/yutwu/vllm-orangina-preview-api:blackwell-harmony-swiglu-clamp-v2
# FROM gitlab-master.nvidia.com:5005/yutwu/vllm-orangina-preview-api:tk-mxfp4-v8-hopper-harmony-v2
#public.ecr.aws/q9t5s3a7/vllm-ci-postmerge-repo:c5b8b5953a2e20e8358d0828aad11d259c073c50

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential cmake git ninja-build && rm -rf /var/lib/apt/lists/*

# Copy and install Triton early for better caching
COPY Harmony/triton /opt/triton
RUN pip install /opt/triton

WORKDIR /app

COPY checkpoints/open-responses-server/ /app

RUN pip install .

RUN chmod +x /app/start.sh

# Create log directory
RUN mkdir -p /app/log

# Define build arguments with default values
ARG LOG_LEVEL=INFO
ARG LOG_FILE_PATH=/app/log/api_adapter.log
ARG MODEL_PATH=/model

# Set environment variables
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    LOG_LEVEL=${LOG_LEVEL} \
    LOG_FILE_PATH=${LOG_FILE_PATH} \
    MODEL_PATH=${MODEL_PATH}

USER root

CMD ["/app/start.sh"] 